### ISSUE TITLE
"content_license" field is unrecognized

### ISSUE THREAD

**Issue by VahidN** [emmettnicholas/StacMan#13]
I'm getting this error lately:
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: "content_license" field is unrecognized
   at StackExchange.StacMan.StacManClient.ParseApiResponse[T](Dictionary`2 jsonObject, String backoffKey)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at StackExchange.StacMan.StacManClient.<>c__DisplayClass17`1.<ParseApiResponse>b__21(Object o)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at StackExchange.StacMan.StacManClient.ParseApiResponse[T](Dictionary`2 jsonObject, String backoffKey)
   at StackExchange.StacMan.StacManClient.<>c__DisplayClass5`1.<GetApiResponse>b__7(String rawData)
```

**Comment by VahidN** [comment]
I was using version: "2.2". Changed it to 2.1 and this fixed the issue.
